create table ads (
id int generated by default as identity primary key ,
title varchar
);

create table users (
id int generated by default as identity primary key ,
name varchar not null
);

create table comments (
id int generated by default as identity primary key ,
content varchar not null
);

create table score_types (
id int generated by default as identity primary key ,
name varchar not null
);

create table ratings (
id int generated by default as identity primary key ,
type_id int references score_types (id) on delete cascade ,
object_id int references ads (id) on delete cascade ,
object_type varchar,
score float check ( score<=5 and score >=0 ),
vote_count int check ( vote_count >= 0 ),
created_at timestamp not null,
updated_at timestamp,
owner_id int references users(id)
);

create table votes (
id int generated by default as identity primary key ,
rating_id int references ratings (id) on delete cascade ,
user_id int references users (id) on delete cascade ,
score int not null check ( score<=5 and score >=0 ),
comment_id int references comments (id) on delete cascade ,
is_accept boolean not null default true,
created_at timestamp not null,
updated_at timestamp
);