### Token by password
POST http://localhost:8081/auth/realms/com-crowdproj-rating/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=com-crowdproj-rating-service&grant_type=password&username=otus-test&password=otus-pass

> {% client.global.set("auth_token", response.body.access_token);
client.global.set("refresh_token", response.body.refresh_token); %}

### Token by refresh token
POST http://localhost:8081/auth/realms/com-crowdproj-rating/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=com-crowdproj-rating-service&grant_type=refresh_token&refresh_token={{refresh_token}}

### Create
POST http://127.0.0.1:8080/api/v1/ratings/create
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "requestType": "create",
  "requestId": "create",
  "rating": {
    "scoreTypeId": "1",
    "objectTypeId": "11",
    "objectId": "111"
  },
  "debug": {
    "stub": "success"
  }
}

### Get unexisted ID
POST http://127.0.0.1:8080/api/v1/ratings/read
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "requestType": "read",
  "requestId": "readId_unknown",
  "rating": {
    "id": "99999"
  },
  "debug": {
    "stub": "badId"
  }
}

### Read With Existed id
POST http://127.0.0.1:8080/api/v1/ratings/read
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "requestType": "read",
  "requestId": "readId",
  "rating": {
    "id": "123"
  },
  "debug": {
    "stub": "success"
  }
}

### Update
POST http://localhost:8080/api/v1/ratings/update
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "requestType": "update",
  "requestId": "updateId",
  "rating": {
    "id": "123",
    "scoreTypeId": "2",
    "objectTypeId": "22",
    "objectId": "222"
  },
  "debug": {
    "stub": "success"
  }
}

### Update with unexistedId
POST http://localhost:8080/api/v1/ratings/update
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "requestType": "update",
  "requestId": "updateId_unknown",
  "rating": {
    "id": "99999",
    "scoreTypeId": "3",
    "objectTypeId": "33",
    "objectId": "333"
  },
  "debug": {
    "stub": "badId"
  }
}

### Delete existed
POST http://localhost:8080/api/v1/ratings/delete
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "requestType": "delete",
  "requestId": "deleteId",
  "rating": {
    "id": "123"
  },
  "debug": {
    "stub": "success"
  }
}

### Delete non-existed
POST http://localhost:8080/api/v1/ratings/delete
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "requestType": "delete",
  "requestId": "deleteId_unknown",
  "rating": {
    "id": "99999"
  },
  "debug": {
    "stub": "badId"
  }
}

### Search by string
POST http://localhost:8080/api/v1/ratings/search
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "requestType": "search",
  "requestId": "search",
  "ratingFilter": {
    "scoreTypeId": "",
    "objectTypeId": "",
    "objectId": ""
  },
  "debug": {
    "stub": "success"
  }
}